{{- if eq .Values.web.ingress.serviceMesh.enabled true }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ .Release.Namespace }}-ingess-gateway
  labels:
    chart: {{ template "rancher-test-gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.web.ingress.domain }}
{{- end}}
