apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: default:spring-{{ .Values.serviceAccountName }}-role
    namespace: default
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: {{ .Values.serviceAccountName }}-spring
subjects:
    - kind: ServiceAccount
      name: default
      namespace: {{ .Values.serviceAccountName }}
