kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: spring-{{ .Values.serviceAccountName }}-role
rules:
  - apiGroups: [""]
    resources: ["services", "pods", "endpoints", "configmaps"]
    verbs: ["get", "watch", "list"]

